### PR TITLE
Update dependencies and prepare for next release

### PR DESCRIPTION
**Pull request by pjones**

### CODE REVIEW

**Comment by pjones** [comment]
Tests are failing due to haskell-servant/servant-blaze#19

I'm not sure why Cabal fails to build a plan when using GHC 8.10.2 but works with older versions.

**Comment by maksbotan** [comment]
Hi! Is this project still alive? Do you perhaps need some help?

We've decided to use the package at our work, but stumbled upon aeson <1.5 dependency. Although that is fixable with Cabal's `allow-newer`, it would be nice to see proper fix.

**Comment by pjones** [comment]
@maksbotan Yep, this project is still alive.

I would absolutely love a PR if you want to put one together.

**Comment by maksbotan** [comment]
Thanks! We'll probably start by updating this PR, what do you think?

**Comment by pjones** [comment]
@maksbotan Sounds good to me.  Thank you!

**Pull request closed without merging**
