### PR TITLE
Update dependencies and prepare for next release

### PR DESCRIPTION
**Pull request by maksbotan**

### CODE REVIEW

**Comment by maksbotan** [comment]
Hi @pjones!
As agreed in #1, I'm trying to fix your existing PR. Looks like you have to push some magic GitHub buttons to make it run CI for me :)

**Comment by pjones** [comment]
This is great!

CI is off and running now.

**Comment by maksbotan** [comment]
Ah, looks like you will have to approve each CI run...

**Comment by pjones** [comment]
Looks like maybe I need to get CI fixed first (it's using deprecated CI features), get that merged onto the main branch, then we can rebase this PR.  What a pain.

**Comment by maksbotan** [comment]
Don't worry, I'll update it tomorrow. Maybe you can grant me some perms on the repo so that you don't have to approve each CI run?

**Comment by pjones** [comment]
@maksbotan 

CI fixes are on https://github.com/sthenauth/openid-connect/tree/biocad-maksbotan/update-pr-1.  If you want to give me permission to push to your forked branch I can push my changes.  Otherwise you can just rebase from my branch.

**Comment by maksbotan** [comment]
Hi @pjones! I've incorporated your CI update, thanks! I've also allowed lens-5.0.

CI seems to pass now, is there something else left to do in this PR?

**Review by pjones — APPROVED** [review]
Looks good.

**Comment by pjones** [comment]
GitHub doesn't like the way we rebased this branch.  I'm going to pull the commits into another branch and merge.

**Comment by pjones** [comment]
Superseded by #4

**Pull request closed without merging**
